name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  branch-naming-rules:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(feature|bugfix|improvement|library|prerelease|release|hotfix|poc)\/[a-z0-9_.-]+$'
          allowed_prefixes: 'feature,bugfix,improvement,library,prerelease,release,hotfix,poc'
          ignore: master,dev,main
          min_length: 5
          max_length: 50

  check-style:
    name: Code style
    needs: [branch-naming-rules]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

  unit-tests:
    name: Unit tests
    needs: [branch-naming-rules]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run test
        run:  go test -coverprofile=coverage.out -v
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.out
